# Numpy

In [1]:
a = 1
b = 2
c = a + b
print(c)

3


## 임포트
파이썬 라이브러리를 사용하기 위해서는 임포트가 필요

In [2]:
import numpy as np

np.__version__

'2.0.2'

In [5]:
# 최신 버전 설치
!pip install numpy

## 배열 *생성*

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])

In [7]:
print(arr1)

[1 2 3 4 5]


In [8]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
arr2 = np.array([[1, 2, 3] ,
                 [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3 = np.array([[[1, 2], [1, 2], [1, 2]],
                 [[1, 2], [1, 2], [1, 2]]])
arr3

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]]])

## 배열의 속성

In [17]:
arr1.shape

(5,)

In [21]:
arr2.shape

(2, 3)

In [24]:
arr3.shape

(2, 3, 2)

In [25]:
type(arr1)

numpy.ndarray

## 인덱싱(Indexing) 과 슬라이싱

In [35]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [36]:
arr1 = np.random.randint(0, 2, 9)
arr1

array([1, 0, 0, 0, 0, 1, 1, 1, 1])

In [37]:
arr2 = np.linspace(0, 1, 9)
arr2

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [38]:
arr[3]

np.int64(8)

In [39]:
arr[0:3]

array([5, 6, 7])

In [41]:
arr[:]

array([5, 6, 7, 8, 9])

In [42]:
arr[-1]

np.int64(9)

In [44]:
arr[-3:]

array([7, 8, 9])

### 불리언 인덱싱(Boolean Indexing)
- Boolean : 참(True), 거짓(False)

In [45]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [46]:
idx = [False, True, False, True, True ]
idx

[False, True, False, True, True]

In [47]:
arr

array([5, 6, 7, 8, 9])

In [48]:
arr >7

array([False, False, False,  True,  True])

In [49]:
arr[arr > 7]

array([8, 9])

### 배열연산

In [54]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [55]:
a+b

array([5, 7, 9])

In [56]:
a+5

array([6, 7, 8])

In [57]:
a.sum()

np.int64(6)

In [58]:
a.mean()

np.float64(2.0)

In [65]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
c = c + 3
c

array([[4, 5, 6],
       [7, 8, 9]])

In [68]:
c

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
c.sum()

np.int64(39)

In [70]:
c.sum(axis = 1)

array([15, 24])

In [71]:
c.mean(), c.mean(axis = 0), c.mean(axis = 1)

(np.float64(6.5), array([5.5, 6.5, 7.5]), array([5., 8.]))

### 형태변경

In [76]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
arr = arr.reshape(4,4)

In [81]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
arr = arr.reshape(4,2,2)
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [83]:
arr.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
arr = arr.reshape(-1, 2, 2)
arr.shape

(4, 2, 2)

In [87]:
arr = arr.reshape(2,-1, 2)
arr.shape

(2, 4, 2)

## 생성

In [ ]:
data = {
    "Name" : ["Jackson", " Emma", "James"],
    "Weight" : [68, 74, 78],
    "Option" : [True,False,True],
    "Type": ["A", "B", "A"]
}

df = pd.DataFrame(data)
df